export enum DocumentTypeEnum {
  SYLLABLES = 'SYLLABLES',
  EXAMS = 'EXAMS',
  WORKED = 'WORKED',
  EXCERCIES = 'EXCERCIES',
  PRESENTATIONS = 'PRESENTATIONS',
  SUMMARY = 'SUMMARY',
  NOTES = 'NOTES'
}
